const {chromium}=require('C:/Users/xxinz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {pathToFileURL}=require('node:url');const path=require('node:path');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(pathToFileURL(path.resolve('md_dark_viewer_working_final.html')).href,{waitUntil:'domcontentloaded'});
 await page.waitForTimeout(700);
 const result=await page.evaluate(async()=>{
  const panels=[...document.querySelectorAll('.cp-picker-top,.custom-theme-head')];
  if(!panels.every(panel=>panel.querySelector('.cp-eyedropper')))throw Error('missing eyedropper');
  const input=document.querySelector('#fmt-color');let changed=0;input.addEventListener('change',()=>changed++);
  window.EyeDropper=class{async open(){return {sRGBHex:'#123456'}}};
  const button=input.closest('.cp-picker-row').querySelector('.cp-eyedropper');button.click();await new Promise(r=>setTimeout(r,30));
  const color=input.value;
  window.EyeDropper=class{async open(){throw new DOMException('cancel','AbortError')}};button.click();await new Promise(r=>setTimeout(r,30));
  const host=document.createElement('div');host.className='preview';host.style.backgroundColor='#222222';host.innerHTML='<code style="background:#242424">test</code><a class="zz-source-chip">chip</a>';document.body.appendChild(host);
  const codeBackground=getComputedStyle(host.firstChild).backgroundColor;
  const before=getComputedStyle(host.lastChild).backgroundColor;
  host.style.setProperty('--t1','#222222');
  const after=getComputedStyle(host.lastChild).backgroundColor;
  const auto=host.querySelector('[data-chip-contrast]')!==null;
  host.firstChild.style.color='#252525';updateInlineCodeInk();
  const corrected=getComputedStyle(host.firstChild).color;
  const adjustedBackground=getComputedStyle(host.firstChild).backgroundColor!==codeBackground;
  host.firstChild.style.color='#ffffff';updateInlineCodeInk();const readablePreserved=!host.firstChild.hasAttribute('data-inline-code-ink');
  host.remove();return {color,changed,codeBackground,before,after,auto,corrected,adjustedBackground,readablePreserved};
 });
 assert.equal(result.color,'123456');assert.equal(result.changed,1);assert.equal(result.codeBackground,'rgb(36, 36, 36)');assert.equal(result.before,result.after);assert.equal(result.auto,false);assert.deepEqual(errors,[]);
 assert.equal(result.corrected,'rgb(37, 37, 37)');assert.ok(result.adjustedBackground&&result.readablePreserved);
 console.log('PASS eyedropper integration, cancellation, no chip inversion, chip background independent of text color');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
