const {chromium}=require('C:/Users/xxinz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {pathToFileURL}=require('node:url');const path=require('node:path');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const page=await browser.newPage({viewport:{width:1400,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(pathToFileURL(path.resolve('md_dark_viewer_working_final.html')).href,{waitUntil:'domcontentloaded'});await page.waitForTimeout(700);
 await page.evaluate(()=>{setMode('edit',false);setEditView('preview')});await page.waitForTimeout(300);
 await page.evaluate(()=>{els.preview.innerHTML='<table><thead><tr><th>학교</th><th>점수</th></tr></thead><tbody><tr><td rowspan="2">B</td><td>10</td></tr><tr><td>11</td></tr><tr><td>A</td><td>2</td></tr></tbody></table>';const option=document.querySelector('#enable-table-filter');option.checked=true;option.dispatchEvent(new Event('change'));});
 assert.equal(await page.locator('.table-filter-button').count(),2);
 await page.locator('.table-filter-button').nth(1).click();await page.getByRole('button',{name:'오름차순 정렬',exact:true}).click();
 assert.equal(await page.locator('#preview tbody tr').first().innerText(),'A\t2');
 await page.locator('.table-filter-button').first().click();await page.locator('.table-filter-values label').filter({hasText:'A'}).locator('input').uncheck();
 assert.equal(await page.locator('.table-filter-section').count(),2);
 await page.locator('.table-filter-section').first().locator('summary').click();assert.equal(await page.locator('.table-filter-values').isVisible(),false);await page.locator('.table-filter-section').first().locator('summary').click();
 assert.equal(await page.getByRole('button',{name:'필터 적용',exact:true}).count(),0);
 assert.equal(await page.locator('.table-filter-button').first().getAttribute('aria-pressed'),'true');
 assert.match(await page.locator('.table-filter-button').first().getAttribute('title'),/필터 적용됨 · 1\/2개 값 표시/);
 assert.equal(await page.locator('#preview tbody tr:not([hidden])').count(),2);
 const clean=await page.evaluate(()=>{const clone=els.preview.cloneNode(true);cleanPreviewHtml(clone);return {rows:clone.querySelectorAll('tbody tr').length,first:clone.querySelector('tbody tr').textContent,controls:clone.querySelectorAll('.table-filter-button,[data-filter-order],[data-filter-hidden]').length,hidden:clone.querySelectorAll('tr[hidden]').length}});
 assert.equal(clean.rows,3);assert.equal(clean.first,'B10');assert.equal(clean.controls,0);assert.equal(clean.hidden,0);
 await page.keyboard.press('Escape');await page.evaluate(()=>{resetTableFilterView(els.preview);els.preview.innerHTML='<table><thead><tr><th>이름</th></tr></thead><tbody><tr><td><strong>굵은 행</strong></td></tr><tr><td>일반 행</td></tr></tbody></table>';installTableFilters()});
 await page.locator('.table-filter-button').click();await page.locator('.table-filter-section').nth(1).locator('summary').click();
 const bold=page.locator('.table-filter-format-options label').filter({hasText:'굵게'}).locator('input');assert.equal(await bold.isDisabled(),false);await bold.check();
 assert.equal(await page.locator('#preview tbody tr:not([hidden])').count(),1);assert.match(await page.locator('#preview tbody tr:not([hidden])').innerText(),/굵은 행/);assert.equal(await page.locator('.table-filter-button').getAttribute('aria-pressed'),'true');
 await bold.uncheck();assert.equal(await page.locator('#preview tbody tr:not([hidden])').count(),2);
 await page.evaluate(()=>{const option=document.querySelector('#enable-table-filter');option.checked=false;option.dispatchEvent(new Event('change'))});assert.equal(await page.locator('.table-filter-button').count(),0);
 await page.locator('#file-list').click({button:'right',position:{x:5,y:5}});assert.ok((await page.locator('.sidebar-context-menu').boundingBox()).width<250);
 assert.deepEqual(errors,[]);console.log('PASS numeric sort, merged-row filter, collapsible value section, format filter, original serialization, option OFF, compact menu');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
